In [1]:
import pandas as pd
import numpy as np

In [3]:
data = {"Name":["Mani","Taaj","Ragul"],"age":[10,0,0]}

In [4]:
df = pd.DataFrame(data)

In [9]:
df.loc[:,["Name","age"]]

    Name  age
0   Mani   10
1   Taaj    0
2  Ragul    0

In [13]:
df.iloc[:,0:1]

    Name
0   Mani
1   Taaj
2  Ragul